### ISSUE TITLE
Shortcut composer stops working in initial program window if an additional window is opened

### ISSUE THREAD

**Issue by andreyuv** [wojtryb/Shortcut-Composer#18]
Hi,

Thank you for this awesome plugin! It helped me switch from Photoshop to Krita for painting.

I have noticed a bug, here are the steps to reproduce it: 

1. Open Krita, create a document and paint something. Checking Shortcut Composer (SC), it should work properly.
2. From the main menu, access Window ->New Window to create a new program window.
3. Notice that in the _old window_ SC has stopped working. However, in the _new window_, it still works.

I am using SC v1.1.0 on Krita 5.1.0 on Windows 11.

I tested this with the Pie Menu and Mouse Trackers features of SC. They all stopped working in the initial window.

Thank you for reading this, let me know if you want me to test anything else.

**Comment by wojtryb** [comment]
Hi, I can confirm it on Linux too.
This may not be a quick fix - I'll check out if I can deal with that somehow.
Thanks for a meaningful issue description! I'll let you know when I'll have more to share.

**Comment by wojtryb** [comment]
Good news - I fixed the issue.
You can check it out by downloading and installing the plugin from `development` branch. I'll close the issue once I test it on Windows. I normally don't use multiple windows in my workflow, so if you found more issues with them, let me know.
Thanks for contributing!

**Comment by andreyuv** [comment]
It seems to be working great now.

Thanks for your help!
