### ISSUE TITLE
Pick transform tool modes stop working

### ISSUE THREAD

**Issue by zarco1794** [wojtryb/Shortcut-Composer#26]
Sometimes Pick transform tool modes stops working. Sometimes it happens when opening another document. When closing and reopening Krita, it works again

![ERROR](https://user-images.githubusercontent.com/39812147/215364647-88b3e9a8-481c-44c0-9a13-b010fe397eb4.png)

**Comment by wojtryb** [comment]
Hi, thank you for reporting.

I believe I fixed your issue. On github you can switch from `main` to `development` then download the .zip again, and import it from krita to check it out.

It will be officially released probably along some new features in v1.2.0
