### ISSUE TITLE
Possible error: Unable to create Split (Handles from Shortcut Ctrl+Alt) the Mesh tool

### ISSUE THREAD

**Issue by zarco1794** [wojtryb/Shortcut-Composer#29]
I may be wrong, but when installing the plugin I am now unable to create "Split" handles with the Ctrl+Alt keyboard shortcut from the Mesh tool. I have the version of Krita 4.3.3, in this version the plugin does not work and the Ctrl+Alt shortcuts to create handles work.
Could it be a plugin bug or is it something from the latest versions of Krita?
![Split](https://user-images.githubusercontent.com/39812147/216682785-f0c4732a-0c06-4f0a-b324-3077f982e1d1.jpg)

**Comment by wojtryb** [comment]
The plugin won't work on 4.3.3. At least 5.1.0 is required.

You can disable the plugin in `Settings > Configure Krita > Python Plugin Manager > untick "Shortcut Composer"`, restart krita and see if the issue remains without the plugin.

`Ctrl+Alt` shortcut works for me, with the plugin enabled.

**Comment by zarco1794** [comment]
It still doesn't work. Maybe it's a problem with my version of Krita and not with the plugin
