### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by Theraa0** [wojtryb/Shortcut-Composer#30]
I just came across this program and followed the installation, but I keep getting this error and the program is not working.
This is from the error box:

`ZeroDivisionError
Python 3.10.9: /usr/bin/python3
Sat Feb  4 01:36:04 2023

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /home/thera/.local/share/krita/pykrita/shortcut_composer/shortcut_composer.py in createActions(self=<shortcut_composer.shortcut_composer.ShortcutComposer object>, window=<PyKrita.krita.Window object>)
   40 
   41         self._manager = ActionManager(window)
   42         self._reload_composer()
   43 
   44     def _create_reload_action(self, window) -> QWidgetAction:
self = <shortcut_composer.shortcut_composer.ShortcutComposer object>
self._reload_composer = <bound method ShortcutComposer._reload_composer ...poser.shortcut_composer.ShortcutComposer object>>

 /home/thera/.local/share/krita/pykrita/shortcut_composer/shortcut_composer.py in _reload_composer(self=<shortcut_composer.shortcut_composer.ShortcutComposer object>)
   59 
   60     def _reload_composer(self) -> None:
   61         """Reload all core actions."""
   62         for action in create_actions():
   63             self._manager.bind_action(action)
action undefined
global create_actions = <function create_actions>

 /home/thera/.local/share/krita/pykrita/shortcut_composer/actions.py in create_actions()
  225     # Use pie menu to pick one of presets from tag specified in settings.
  226     # Set tool to FREEHAND BRUSH if current tool does not allow to paint
  227     templates.PieMenu(
  228         name="Pick brush presets (green)",
  229         controller=controllers.PresetController(),
global templates = <module 'templates' from '/home/thera/.local/sha...pykrita/shortcut_composer/templates/__init__.py'>
templates.PieMenu = <class 'templates.pie_menu.PieMenu'>
name undefined
controller undefined
global controllers = <module 'core_components.controllers' from '/hom...omposer/core_components/controllers/__init__.py'>
controllers.PresetController = <class 'core_components.controllers.view_controllers.PresetController'>
global instructions = <module 'core_components.instructions' from '/ho...mposer/core_components/instructions/__init__.py'>
instructions.SetBrushOnNonPaintable = <class 'core_components.instructions.set_brush_strategy.SetBrushOnNonPaintable'>
values undefined
global TagConfigValues = <class 'data_components.writable_values.TagConfigValues'>
global Config = <enum 'Config'>
Config.TAG_GREEN = <Config.TAG_GREEN: 'Tag (green)'>
Config.TAG_GREEN_VALUES = <Config.TAG_GREEN_VALUES: 'Tag (green) values'>
background_color undefined
global QColor = <class 'PyQt5.QtGui.QColor'>
active_color undefined

 /home/thera/.local/share/krita/pykrita/shortcut_composer/templates/pie_menu.py in __init__(self=<templates.pie_menu.PieMenu object>, name='Pick brush presets (green)', controller=<core_components.controllers.view_controllers.PresetController object>, values=['Basic mix soft', 'Basic mix', 'Basic tip defau...Eraser circle', 'Ink gpen 10', 'Smudge textured'], instructions=[<core_components.instructions.set_brush_strategy.SetBrushOnNonPaintable object>], pie_radius_scale=1.0, icon_radius_scale=1.0, background_color=<PyQt5.QtGui.QColor object>, active_color=<PyQt5.QtGui.QColor object>, short_vs_long_press_time=None)
   93 
   94         self._labels = self._create_labels(values)
   95         self._style = PieStyle(
   96             pie_radius_scale=pie_radius_scale,
   97             icon_radius_scale=icon_radius_scale,
self = <templates.pie_menu.PieMenu object>
self._style undefined
global PieStyle = <class 'templates.pie_menu_utils.pie_style.PieStyle'>
pie_radius_scale = 1.0
icon_radius_scale = 1.0
icons_amount undefined
builtinlen = <built-in function len>
self._labels = []
background_color = <PyQt5.QtGui.QColor object>
active_color = <PyQt5.QtGui.QColor object>

 /home/thera/.local/share/krita/pykrita/shortcut_composer/templates/pie_menu_utils/pie_style.py in __init__(self=PieStyle(), pie_radius_scale=1.0, icon_radius_scale=1.0, icons_amount=0, background_color=<PyQt5.QtGui.QColor object>, active_color=<PyQt5.QtGui.QColor object>)
   51             * Config.PIE_GLOBAL_SCALE.read())
   52 
   53         self.icon_radius = self._pick_icon_radius()
   54         self.widget_radius = self.pie_radius + self.icon_radius
   55         self.deadzone_radius = self._pick_deadzone_radius()
self = PieStyle()
self.icon_radius undefined
self._pick_icon_radius = <bound method PieStyle._pick_icon_radius of PieStyle()>

 /home/thera/.local/share/krita/pykrita/shortcut_composer/templates/pie_menu_utils/pie_style.py in _pick_icon_radius(self=PieStyle())
   79             * Config.PIE_ICON_GLOBAL_SCALE.read()
   80         )
   81         max_icon_size = round(self.pie_radius * math.pi / self._icons_amount)
   82         return min(icon_radius, max_icon_size)
   83 
max_icon_size undefined
builtinround = <built-in function round>
self = PieStyle()
self.pie_radius = 124
global math = <module 'math' from '/usr/lib/python3.10/lib-dynload/math.cpython-310-x86_64-linux-gnu.so'>
math.pi = 3.141592653589793
self._icons_amount = 0
ZeroDivisionError: float division by zero
    __cause__ = None
    __class__ = <class 'ZeroDivisionError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of ZeroDivisionError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of ZeroDivisionError object>
    __doc__ = 'Second argument to a division or modulo operation was zero.'
    __eq__ = <method-wrapper '__eq__' of ZeroDivisionError object>
    __format__ = <built-in method __format__ of ZeroDivisionError object>
    __ge__ = <method-wrapper '__ge__' of ZeroDivisionError object>
    __getattribute__ = <method-wrapper '__getattribute__' of ZeroDivisionError object>
    __gt__ = <method-wrapper '__gt__' of ZeroDivisionError object>
    __hash__ = <method-wrapper '__hash__' of ZeroDivisionError object>
    __init__ = <method-wrapper '__init__' of ZeroDivisionError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of ZeroDivisionError object>
    __lt__ = <method-wrapper '__lt__' of ZeroDivisionError object>
    __ne__ = <method-wrapper '__ne__' of ZeroDivisionError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of ZeroDivisionError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of ZeroDivisionError object>
    __repr__ = <method-wrapper '__repr__' of ZeroDivisionError object>
    __setattr__ = <method-wrapper '__setattr__' of ZeroDivisionError object>
    __setstate__ = <built-in method __setstate__ of ZeroDivisionError object>
    __sizeof__ = <built-in method __sizeof__ of ZeroDivisionError object>
    __str__ = <method-wrapper '__str__' of ZeroDivisionError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ('float division by zero',)
    with_traceback = <built-in method with_traceback of ZeroDivisionError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/home/thera/.local/share/krita/pykrita/shortcut_composer/shortcut_composer.py", line 42, in createActions
    self._reload_composer()
  File "/home/thera/.local/share/krita/pykrita/shortcut_composer/shortcut_composer.py", line 62, in _reload_composer
    for action in create_actions():
  File "/home/thera/.local/share/krita/pykrita/shortcut_composer/actions.py", line 227, in create_actions
    templates.PieMenu(
  File "/home/thera/.local/share/krita/pykrita/shortcut_composer/templates/pie_menu.py", line 95, in __init__
    self._style = PieStyle(
  File "/home/thera/.local/share/krita/pykrita/shortcut_composer/templates/pie_menu_utils/pie_style.py", line 53, in __init__
    self.icon_radius = self._pick_icon_radius()
  File "/home/thera/.local/share/krita/pykrita/shortcut_composer/templates/pie_menu_utils/pie_style.py", line 81, in _pick_icon_radius
    max_icon_size = round(self.pie_radius * math.pi / self._icons_amount)
ZeroDivisionError: float division by zero

`

**Comment by wojtryb** [comment]
Hi,

I fixed this error some time ago, but it hasn't been released yet.
On github, you can change `main` to `development`, and then download and install the plugin.

**Comment by Theraa0** [comment]
Alright, thank you!
