### ISSUE TITLE
Pie Menus and their Settings are not displayed correctly on XFCE desktop enviroment

### ISSUE THREAD

**Issue by Axis4s** [wojtryb/Shortcut-Composer#41]
![image](https://user-images.githubusercontent.com/97393974/234730644-4f4d1b90-edbf-4f5e-923b-a3b8069436b9.png)
![image](https://user-images.githubusercontent.com/97393974/234731266-ac0f779d-6cac-4cac-a713-b9605950f401.png)
So not sure what happen but sometimes, the Config menu for pies are invisible, i think this happens when you quickly tap the composer pie shortcuts
![image](https://user-images.githubusercontent.com/97393974/234731849-73db8a95-669a-407d-97f7-f8b2866ab88e.png)
and sometimes it takes the focus off the krita's main window

**Comment by Axis4s** [comment]
Look at the mouse cursor in the first picture.
It should be a basic outline spherical cursor. That's the cursor used when
your pen is directly on Krita's Canvas.
Instead the cursor is on default. It shouldn't be like that.
And that area where I'm hovering at is exactly where the Config window for
the pie is located at. The 2nd Picture is to make it more clearer, I even
have one of the tools selected

**Comment by wojtryb** [comment]
You shouldn't really click on the canvas or move your cursor out of the pie when selecting an icon. It's fine that the cursor is not interacting with krita main window.

If you mean that when entering the edit mode the window is there, but is not displayed - it's probably some display error specific to your distribution, and I can't do much about it.

Are you using appimage version of krita?

**Comment by Axis4s** [comment]
I was using the AUR version of krita

**Comment by wojtryb** [comment]
Appimage is the only officially supported version of krita. It contains some custom Qt patches.

I can't guarantee it's gonna work on that version, but it's worth trying

**Comment by wojtryb** [comment]
Is there any progress with tracking down your issues? Did you maybe try to use krita from .appimage?

**Comment by Axis4s** [comment]
> Is there any progress with tracking down your issues? Did you maybe try to use krita from .appimage?

sorry for the late response, bug still persists on the appimage version

**Comment by Axis4s** [comment]
![image](https://user-images.githubusercontent.com/97393974/236568157-0b409a2e-9ce0-4454-970a-df80de9778bc.png)
![Screenshot_2023-05-05_16-59-55](https://user-images.githubusercontent.com/97393974/236568234-674c90eb-2630-4994-8356-e3d5b2a5ea73.png)
![Screenshot_2023-05-05_17-00-36](https://user-images.githubusercontent.com/97393974/236568247-61b789a9-509f-4430-b05d-321966f8bc25.png)

btw here if you still didn't understand, look at that stroke i did on the canvas, these are 2 separate screenshots and one with both overlayed on top of eachother

**Comment by Axis4s** [comment]
![image](https://user-images.githubusercontent.com/97393974/236570426-b356dd21-4206-4a56-9fb4-815e3ece6e0c.png)
here's a more clear view, i disabled my display compositor, so transparency effects are disabled
there's the pie settings window

**Comment by wojtryb** [comment]
I'm afraid I won't be able to help you much here.

Both Pie and its settings are technically separate windows with usual frames disabled. They are marked in Qt5 as "Tools" which should result in OS treating them more like some kind of pop-up which can stay on top for some time, than a fully separate window. This seems to be respected correctly by Windows 10, 11 as well as Gnome and KDE Plasma.

While I'll be happy to have the plugin working on as many environments as possible, covering all of them is out of my scope. It's probably possible to fix your issue by trying out different settings for those windows, but I don't think I'll be able to take care of it in the nearest future.

**Comment by Axis4s** [comment]
> I'm afraid I won't be able to help you much here.
> 
> Both Pie and its settings are technically separate windows with usual frames disabled. They are marked in Qt5 as "Tools" which should result in OS treating them more like some kind of pop-up which can stay on top for some time, than a fully separate window. This seems to be respected correctly by Windows 10, 11 as well as Gnome and KDE Plasma.
> 
> While I'll be happy to have the plugin working on as many environments as possible, covering all of them is out of my scope. It's probably possible to fix your issue by trying out different settings for those windows, but I don't think I'll be able to take care of it in the nearest future.

Im using EndeavourOS with XFCE, XFCE Is a lightweight desktop environment

**Comment by wojtryb** [comment]
As the plugin is working on Gnome, Plasma and Windows, your desktop environment is most likely the problem.

I believe XFCE does not fully support Qt5 window flags, or it's a bug in handling tools. If you really like to further investigate the issue, you can go to `~/.local/share/krita/pykrita` and remove the `Qt.Tool` flag from files:
- `shortcut_composer/templates/pie_menu_utils/pie_widget.py`
- `shortcut_composer/templates/pie_menu_utils/settings_gui/pie_settings.py`

This would make the OS treat both the pie and its settings as usual windows. It can result in things like krita losing focus when they appear, but could fix your problems (although this is a shot in a dark). That would confirm XFCE has a bug related to Qt.Tool flag.

Anyway, sorry but I can't really support niche environments like that :)
