### ISSUE TITLE
Fot information, with my wacom cintiq pro tablet, touch shortcut affected to wacom material (pencil button or tablet button) do not work on the 1.4 version. I had to come back to the 1.2

### ISSUE THREAD

**Issue by BertConstanty** [wojtryb/Shortcut-Composer#62]
**General info**
- Plugin version: ... [example: v1.4.0]
- Operating System: ... window 11

**Bug description**
Fot information, with my wacom cintiq pro tablet, touch shortcut affected to wacom material (pencil button or tablet button) do not work on the 1.4 version. I had to come back to the 1.2

Ideally:
1.3.2 is working

**Comment by wojtryb** [comment]
Hi, I can't really support inputs imitating the keyboard. They usually work, but it depends on it's driver, but when they don't - there's not much I can do.

1.4.0 changed how the key release is detected to get rid of the bug with non-latin keyboard layouts. Probably this is what changed the behavior.

Unluckily fixing this big is more important than having compatibility with Cintiq device, as I can't guarantee it wouldn't break anyway with driver update.

**Comment by BertConstanty** [comment]
Indeed it seems complicated, thank you anyway i will stay on the previous rev. I hope one day your plugin will be intergrated into krita as it is surch an big step forward. have a good day.
