### ISSUE TITLE
Quirks on arch linux

### ISSUE THREAD

**Issue by Zerogaku** [wojtryb/Shortcut-Composer#88]
**General info**
- Plugin version: v1.5.3
- Operating System:  Arch linux

**Bug description**
I'm using krita on a tiling window manager and encountered some difficulty trying to use the plugin, I'm certain I have the required dependencies so it's likely due to the window manager, basically the pie menus will sometimes just not respond, or display properly, also I'm not sure if the pie menu being squared can be fixed, then there's this strange floating icon that's floating, I'm not sure what it's meant for

https://github.com/wojtryb/Shortcut-Composer/assets/144664603/c1ae1bf9-db19-4767-a218-45c36b8641a3

**Comment by wojtryb** [comment]
Hi, I am afraid there is not much that can be done here.

Pie menus are in fact just windows, but with flags marking them borderless and transparent. That is supported by Windows, Gnome and KDE Plasma, but your setup clearly struggles to display any transparency.

The pie animations also seem to be broken, probably from the same reason.

As for the button - it is a setting button from a different action, but I do not know why it stays on like this, while other buttons do not.

Anyway, I cannot help you much in here, as you are running an unsupported distro and your window manager probably was not designed with windows popping up like so in mind. I do not think there is a way to make it work there properly.

**Comment by wojtryb** [comment]
Since this issue is specific to unsupported linux distro (or more specifically graphical shell) I am closing the issue.

I am not sure that features provided by the plugin can be made supported there.
