### ISSUE TITLE
Cursor tracker flicker 

### ISSUE THREAD

**Issue by HubertKrzykalski** [wojtryb/Shortcut-Composer#90]
**General info**
- Plugin version: v1.5.3
- Operating System: Windows 10

**Bug description**
Whenever I use undo scroll, there are flicks after a horizontal move. Other cursor trackers like layer scroll work fine as shown in the video.
And one question unrelated to this ticket. Is Scroll Canvas zoom or Rotation supposed to be slower than default counterparts?

https://github.com/wojtryb/Shortcut-Composer/assets/46659437/158b3e74-510a-45c6-a119-ae6cd77e1752

**Comment by wojtryb** [comment]
Hi, thank you for reporting!

I managed to recreate the issue - it is not OS specific, and must have been introduced months ago. I have a temporary fix, so I will try to release a proper solution soon.

For the unrelated question: zoom and rotation in the plugin are discrete (you can have 1° or 2°, but not 1.5°). This may feel less fluid then the original one. I think it was needed to fix some issues some time ago, but I'm not sure it is the right solution.
But if you mean that these are less sensitive, then you can tweak that in general plugin options (Tools > Scripts > Configure Shortcut Composer)

**Comment by HubertKrzykalski** [comment]
Glad it will be fixed.

For the unrelated question: I would need to make the sensitivity 2.5 for the cursor rotate tool to work similarly to the default one. Altho by doing that other cursor-related tools from the addon become hard to use as it is hard to control them. Either way, it isn't a big deal to me. I can just not use it. Also love the addonm been used for a few days and this is such a level up to Krita. Keep up the good work! Pozdrawiam (:

**Comment by wojtryb** [comment]
I just released 1.5.4 with a fix for this issue.

Cursor trackers should have their local settings, but honestly - this and many other actions just were not improved much since pie menus became the core feature of this plugin. Maybe someday.

Również pozdrawiam :)
