### ISSUE TITLE
Transform Pie or shortcut doesnt work if you have move tool on ctrl+leftclick

### ISSUE THREAD

**Issue by HubertKrzykalski** [wojtryb/Shortcut-Composer#93]
**General info**
- Plugin version: v1.3.4
- Operating System: Win10

**Bug description**
If you have move tool set to ctrl+left mouse click, transform modes set to also control, like ctrl+t, as you click the ctrl+t and choose one 
of the options in the pie, it doesn't work, as the Krita, decides to 1. go into transform tool with proper mode, then because of ctrl still being clicked, 2. goes into move tool. 3. lastly goes again into the transform tool, and as Krita doesn't save the last transform mode, you have the default "free" option.

Ideally:
Don't use ctrl as a shortcut for transform pie.
https://github.com/user-attachments/assets/e0089058-45f0-4145-a53e-c3208369699c

**Comment by HubertKrzykalski** [comment]
https://github.com/user-attachments/assets/5022987b-5312-4ac5-a657-7b23fd28920f

**Comment by HubertKrzykalski** [comment]
Reuploading the screen recording, previous one was embedded wrongly

**Comment by wojtryb** [comment]
Hi and thank you for reporting.

This issue may not be possible to solve, and I do not really know what to do with it.

Actions for selecting transform tool modes are a rather nasty hack, as krita does not support that at all. I do not like having that in my plugin, but the action itself feels useful enough to accept the problems that come with the hack. 

When you release the ctrl key, krita handles going back to the transform tool on its own, and I cannot change it inside the plugin. 

Readme of my plugin warns about possible clashes with krita's "canvas input" system, and that is all I can do in that matter.

**Comment by HubertKrzykalski** [comment]
Hello, 
I thought that it would be on the Krita site, and not fixable. Not a huge problem honestly. Thanks for the reply!
